# Generated by Django 3.0.7 on 2021-03-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exprecords', '0002_auto_20210309_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exprecord',
            name='date',
            field=models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.'),
        ),
    ]
