# Generated by Django 3.0.7 on 2021-03-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exprecords', '0004_exprecord_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exprecord',
            name='proof',
            field=models.FileField(upload_to='proofs/'),
        ),
    ]
