# Generated by Django 3.0.7 on 2021-03-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exprecords', '0006_auto_20210310_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exprecord',
            name='proof',
            field=models.FileField(upload_to='proofs/'),
        ),
    ]
