# Generated by Django 3.0.7 on 2021-03-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exprecords', '0007_auto_20210316_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exprecord',
            name='description',
            field=models.TextField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=4096),
        ),
    ]
