# Generated by Django 3.0.7 on 2021-03-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exprecords', '0008_auto_20210316_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exprecord',
            name='proof',
            field=models.FileField(blank=True, upload_to='proofs/'),
        ),
    ]
