# Generated by Django 3.0.7 on 2021-03-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exprecords', '0009_auto_20210316_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exprecord',
            name='date',
            field=models.DateField(),
        ),
    ]
